services:
  app:
    build: .
    container_name: financial-app
    ports:
      - "8501:8501"
    environment:
      # CHANGE THIS: Use your Cloud URI (it looks like neo4j+s://xxxx.databases.neo4j.io)
      - NEO4J_URI=neo4j+s://da0b2bf9.databases.neo4j.io
      - NEO4J_USER=neo4j
      # Your Cloud Password (not the local one)
      - NEO4J_PASSWORD=AxMRXm1AVaAe9MOuLDIn4whN1vCIqnBVPG0Wv1Vt-zg
    volumes:
      - ./shared_data:/app/database

  worker:
    build: .
    container_name: financial-worker
    command: python worker.py
    environment:
      # CHANGE THIS: Match the URI above
      - NEO4J_URI=neo4j+s://da0b2bf9.databases.neo4j.io
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=AxMRXm1AVaAe9MOuLDIn4whN1vCIqnBVPG0Wv1Vt-zg
    volumes:
      - ./shared_data:/app/database