import pandas as pd
import numpy as np

def enrich_data(df):
    """
    Applies shared feature engineering logic.
    Expects a DataFrame with 'close' and 'sentiment_score' columns.
    """
    # Defensive copy to avoid SettingWithCopy warnings
    df = df.copy()
    
    # Sort to ensure rolling windows work correctly
    if 'timestamp' in df.columns:
        df = df.sort_values('timestamp')
    
    # --- 1. VOLATILITY FEATURES (The "Pulse") ---
    # Daily Returns
    df['pct_change'] = df['close'].pct_change().fillna(0)
    
    # 7-Day Rolling Volatility (Annualized)
    # This amplifies small moves so the neural network notices them
    df['volatility_7d'] = df['pct_change'].rolling(window=7).std() * np.sqrt(252)
    
    # Volatility Spike: Is today 50% more volatile than the last month?
    df['vol_30d_avg'] = df['volatility_7d'].rolling(window=30).mean()
    # Handle division by zero
    df['vol_30d_avg'] = df['vol_30d_avg'].replace(0, 0.001)
    
    # Feature: 1.0 if spiking, 0.0 if calm
    df['volatility_shock'] = (df['volatility_7d'] > (1.5 * df['vol_30d_avg'])).astype(float)

    # --- 2. SENTIMENT MOMENTUM (The "Panic") ---
    # Is sentiment dropping rapidly compared to the 2-week average?
    df['sentiment_ma_14'] = df['sentiment_score'].rolling(window=14).mean()
    df['sentiment_shock'] = df['sentiment_score'] - df['sentiment_ma_14']

    # --- 3. PRICE VELOCITY ---
    # Simple momentum: Price vs 50-day moving average
    df['ma_50'] = df['close'].rolling(window=50).mean()
    df['trend_deviation'] = (df['close'] - df['ma_50']) / df['ma_50']

    # Cleanup NaNs generated by rolling windows
    df = df.fillna(0)
    
    return df